admin_app/urls.py
from django.urls import path
from . import views

app_name = 'admin_app'

urlpatterns = [
    path('', views.CustomMyAdminLoginView.as_view(), name='login'),
    path('logout/', views.CustomMyAdminLogoutView.as_view(), name='logout'),
    path('protected/', views.CustomMyAdminHomeView.as_view(), name='home'),
    
    path('protected/emails/', views.SentEmailsView.as_view(), name='email_table'),
    path('protected/email/<int:pk>/', views.SentEmailDetailView.as_view(), name='email_detail'),
    
    path('protected/project/new/', views.ProjectAddView.as_view(), name='project_new'),
    path('protected/project/<slug:slug>/', views.ProjectEditView.as_view(), name='project_edit'),
    path('protected/project/<slug:slug>/delete/', views.ProjectDeleteView.as_view(), name='project_delete'),
    
    path('protected/tag/new/', views.TagAddView.as_view(), name='tag_new'),
    path('protected/tag/<slug:slug>/', views.TagEditView.as_view(), name='tag_edit'),
    path('protected/tag/<slug:slug>/delete/', views.TagDeleteView.as_view(), name='tag_delete'),
    
    path('projects/toggle/<int:pk>/<str:field>/', views.ToggleBooleanFields.as_view(), name='toggle_boolean'),
]

main_app/urls.py
from django.urls import path
from . import views

app_name = 'main_app'

urlpatterns = [
    path('', views.MainHomeView.as_view(), name='home'),
    path('about-me/', views.AboutMeView.as_view(), name='about_me'),
    
]

portifolio_project/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings

app_name='portifolio_project'

urlpatterns = [
    path('', include('main_app.urls')),
    path('projects/', include('projects_app.urls')),
    path('admin/', include(('admin_app.urls', 'admin_app'), namespace='admin-a')),
    path('captcha/', include('captcha.urls')),
]

# Disable the django admin and reload script if debug is False
if settings.DEBUG:
    urlpatterns.append(path('dj-admin/', admin.site.urls))
    urlpatterns.append(path("__reload__/", include("django_browser_reload.urls")))
    
    # Static and media files configuration
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin_app/models.py
from django.db import models
from django.contrib.auth.models import User

projects_app/models.py
from __future__ import annotations
from django.db import models
from django.utils.text import slugify
from utils.img_processor import process_img
import utils.constants as consts

# Model for Projects
class ProjectModel(models.Model):
    name = models.CharField(max_length=40)
    slug = models.SlugField(unique=True, blank=True)
    short_desc = models.TextField(max_length=400)
    long_desc= models.TextField(null=True, blank=True)
    img_icon = models.ImageField(upload_to=consts.MEDIA_PROJECT.name, null=True, blank=True)
    tags = models.ManyToManyField('TagModel', default='', blank=True)
    visibility = models.BooleanField(default=True)
    featured = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
    
    def save(self, *args, **kwargs):
        # Automatically generate a slug if not provided
        # Ensure the slug is unique by appending a number if necessary
        if not self.slug:
            base_slug = slugify(self.name)
            slug = base_slug
            count = 1
            while ProjectModel.objects.filter(slug=slug).exists():
                slug = f'{base_slug}-{count}'
                count += 1
            self.slug = slug
        
        # Process the image icon if it exists
        # If the project already exists, check if the image has changed
        if self.pk:
            old = ProjectModel.objects.filter(pk=self.pk).only("img_icon").first()
            if old and old.img_icon != self.img_icon and self.img_icon:
                self.img_icon = process_img(self.img_icon, self.name)
        else:
            if self.img_icon:
                self.img_icon = process_img(self.img_icon, self.name)
            
        super().save(*args, **kwargs)
    
    def __str__(self) -> str:
        return f'{self.name}'

# Models for the tags associated with projects
class TagModel(models.Model):
    name = models.CharField(max_length=20)
    slug = models.SlugField(unique=True, blank=True)
    short_desc = models.TextField(max_length=200)
    long_desc = models.TextField(null=True, blank=True)
    img_icon = models.ImageField(upload_to=consts.MEDIA_TAG.name, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)
        
    def save(self, *args, **kwargs):
        # Automatically generate a slug if not provided
        # Ensure the slug is unique by appending a number if necessary
        if not self.slug:
            base_slug = slugify(self.name)
            slug = base_slug
            count = 1
            while TagModel.objects.filter(slug=slug).exists():
                slug = f'{base_slug}-{count}'
                count += 1
            self.slug = slug
        
        # Process the image icon if it exists
        # If the tag already exists, check if the image has changed
        if self.pk:
            old = TagModel.objects.filter(pk=self.pk).only("img_icon").first()
            if old and old.img_icon != self.img_icon and self.img_icon:
                self.img_icon = process_img(self.img_icon, self.name)
        else:
            if self.img_icon:
                self.img_icon = process_img(self.img_icon, self.name)
        
        super().save(*args, **kwargs)
            
    def __str__(self) -> str:
        return f'{self.name}'

admin_app/forms.py
from django import forms
from django.contrib.auth import authenticate
from projects_app.models import ProjectModel, TagModel

# Custom authentication form for user login
class CustomMyAdminLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))
    
    error_messages = {
        'invalid_login': "Username or password is incorrect.",
    }
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)
    
    # Customizing the form fields to automatically handle the request and authenticate the user
    def clean(self):
        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')

        if username and password:
            self.user_cache = authenticate(self.request, username=username, password=password)
            if self.user_cache is None:
                raise forms.ValidationError(
                    self.error_messages['invalid_login'],
                    code='invalid_login',
                )
        return self.cleaned_data
    
    # Method to get the authenticated user from the form
    def get_user(self):
        return getattr(self, 'user_cache', None)

# Form for creating or updating a project    
class ProjectForm(forms.ModelForm):
    class Meta:
        model = ProjectModel
        fields = ['name', 'short_desc', 'long_desc', 'img_icon', 'tags', 'visibility', 'featured']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'input-name', 
                'placeholder': 'Project name'}),
            'short_desc': forms.Textarea(attrs={
                'id': 'short-desc', 
                'class': 'input-short-desc',
                'placeholder': 'Enter a short description..',
                'maxlength': 400}),
            'long_desc': forms.Textarea(attrs={
                'id': 'long-desc',
                'class': 'input-long-desc',
                'placeholder': 'Enter a longer description..'}),
            'img_icon': forms.ClearableFileInput(attrs={
                'class': 'input-img',
                'accept': 'image/*'
            }),
            'tags': forms.CheckboxSelectMultiple(),
        }

# Form for creating or updating a tag        
class TagsForm(forms.ModelForm):
    class Meta:
        model = TagModel
        fields = ['name', 'short_desc', 'long_desc', 'img_icon']
        widgets = {
            'name': forms.TextInput(attrs={
                'class': 'input-name', 
                'placeholder': 'Project name'}),
            'short_desc': forms.Textarea(attrs={
                'id': 'short-desc', 
                'class': 'input-short-desc',
                'placeholder': 'Enter a short description..',
                'maxlength': 200}),
            'long_desc': forms.Textarea(attrs={
                'id': 'long-desc',
                'class': 'input-long-desc',
                'placeholder': 'Enter a longer description..'}),
            'img_icon': forms.ClearableFileInput(attrs={'class': 'input-img'}),
        }
    

admin_app/views.py
from typing import Any
from django.views.generic.edit import FormView, CreateView, UpdateView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login, logout
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse
from django.views import View
from django.http import JsonResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CustomMyAdminLoginForm, ProjectForm, TagsForm
from .mixins import ProjectFormMixin, TagFormMixin
from projects_app.models import ProjectModel, TagModel
from main_app.models import EmailModel

import logging
logger = logging.getLogger(__name__)

# Custom admin views for handling login
class CustomMyAdminLoginView(FormView):
    template_name = 'admin_app/login.html'
    form_class = CustomMyAdminLoginForm
    
    def get_success_url(self):
        return reverse('admin_app:home') + '?switch_state=projects'
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs
    
    # Customizing the form validation to handle login and logging
    def form_valid(self, form):
        user = form.get_user()
        if user is not None:
            login(self.request, user)
            logger.info(f"Successful login for user: {user.username} of IP: {self.request.META.get('REMOTE_ADDR')}")
            return redirect(self.get_success_url())
        else:
            logger.warning(f"Login attempt failed for user: {form.cleaned_data.get('username')} of IP: {self.request.META.get('REMOTE_ADDR')}")
            return self.form_invalid(form)

# Custom logout view to handle user logout
class CustomMyAdminLogoutView(View):
    def post(self, request, *args, **kwargs):
        logout(request)
        return redirect('admin_app:login')

# Custom admin home view to list projects and tags with pagination and ordering
class CustomMyAdminHomeView(LoginRequiredMixin, ListView):
    template_name = 'admin_app/home.html'
    login_url = 'admin_app:login'
    context_object_name = 'objects'
    paginate_by = 10
    ordering = ['-id']

    def get_ordering(self):
        ordering = self.request.GET.get('order_by', '-id')
        return ordering
    
    # Customizing the queryset to switch between projects and tags based on the request parameter
    def get_queryset(self):
        switch = self.request.GET.get('switch_state')
        ordering = self.get_ordering()
        
        if switch == 'tags':
            return TagModel.objects.all().order_by(ordering)

        return ProjectModel.objects.all().order_by(ordering)
    
    # Customizing the context data to include additional information for the template
    def get_context_data(self, **kwargs) -> dict[str, Any]:
        context = super().get_context_data(**kwargs)
        context['switch_state'] = self.request.GET.get("switch_state", "tags")
        querydict = self.request.GET.copy()
        querydict.pop('page', None)
        context['querystring'] = querydict.urlencode()
        return context

# Custom view for displaying the list of sent emails
class SentEmailsView(LoginRequiredMixin, ListView):
    model = EmailModel
    context_object_name = 'emails'
    template_name = 'admin_app/email_table.html'
    login_url = 'admin_app:login'
    paginate_by = 10
    ordering = ['-id']
    
    def get_ordering(self):
        ordering = self.request.GET.get('order_by', '-id')
        return ordering

# Custom View for displaying the details of a sent email  
class SentEmailDetailView(LoginRequiredMixin, DetailView):
    model = EmailModel
    context_object_name = 'email'
    template_name = 'admin_app/email_detail.html'

# Custom views for handling project management
# ProjectAddView used for creating new projects
class ProjectAddView(LoginRequiredMixin, ProjectFormMixin, CreateView):
    model = ProjectModel
    form_class = ProjectForm
    login_url = 'admin_app:login'

# ProjectEditView used for editing existing projects
class ProjectEditView(LoginRequiredMixin, ProjectFormMixin, UpdateView):
    model = ProjectModel
    form_class = ProjectForm
    login_url = 'admin_app:login'

# ProjectDeleteView used for deleting projects
class ProjectDeleteView(LoginRequiredMixin, View):
    login_url = 'admin_app:login'
    def post(self, request, slug):
        obj = get_object_or_404(ProjectModel, slug=slug)
        obj.delete()
        return JsonResponse({'success': True})

# Custom views for handling tag management
# TagAddView used for creating new tags
class TagAddView(LoginRequiredMixin, TagFormMixin, CreateView):
    model = TagModel
    form_class = TagsForm
    login_url = 'admin_app:login'

# TagEditView used for editing existing tags
class TagEditView(LoginRequiredMixin, TagFormMixin, UpdateView):
    model = TagModel
    form_class = TagsForm
    login_url = 'admin_app:login'

# TagDeleteView used for deleting tags
class TagDeleteView(LoginRequiredMixin, View):
    login_url = 'admin_app:login'
    def post(self, request, slug):
        obj = get_object_or_404(TagModel, slug=slug)
        obj.delete()
        return JsonResponse({'success': True})

# Custom view for toggling boolean fields in the project model
class ToggleBooleanFields(LoginRequiredMixin, View):
    login_url = 'admin_app:login'
    def post(self, request, pk, field):
        project = get_object_or_404(ProjectModel, pk=pk)
        
        if field in ['visibility', 'featured']:
            value = request.POST.get('value') == 'on'
            setattr(project, field, value)
            project.save()
        
        return redirect(request.META.get('HTTP_REFERER', 'admin_app:home'))

admin_app/templates/admin_app/email_table.html
{% extends "global/base.html" %}
{% load template_filters %}
{% load static %}


{% block content %}
    {% block extra_css %}
        <link rel="stylesheet" href="{% static 'global/css/pages/email_table.css' %}">
        <link rel="stylesheet" href="{% static 'global/css/partials/paginator.css' %}">
    {% endblock extra_css %}
    <div class='container'>
        <div class='container-title'>
            <form method='get'>
                <h1>Emails - Admin</h1>
                <a href="{% url 'admin_app:home' %}?switch_state=projects" class="new-register">Home - Admin</a>            
            </form>

        </div>
        <div class='register-table-div'>
        <table class='register-table'>
            <thead>
                <tr>
                    <th class='col-id'><a href="?order_by={% if request.GET.order_by == 'id' %}-id{% else %}id{% endif %}">ID</a></th>
                    <th class='col-name'><a href="?order_by={% if request.GET.order_by == 'name' %}-name{% else %}name{% endif %}">NAME</a></th>
                    <th class='col-email'><a href="?order_by={% if request.GET.order_by == 'email' %}-email{% else %}email{% endif %}">EMAIL</th></a>
                    <th class='col-subject'><a href="?order_by={% if request.GET.order_by == 'subject' %}-subject{% else %}subject{% endif %}">SUBJECT</th></a>
                    <th class='col-email-send'><a href="?order_by={% if request.GET.order_by == 'email_send' %}-email_send{% else %}email_send{% endif %}">EMAIL SENT</a></th>
                    <th class='col-created-at'><a href="?order_by={% if request.GET.order_by == 'created_at' %}-created_at{% else %}created_at{% endif %}">CREATED AT</a></th>
                </tr>
            </thead>

            <tbody>
                {% for obj in emails %}
                    <tr>
                        <td class='col-id' ><a href="{% url 'admin_app:email_detail' pk=obj.id %}">{{ obj.id }}</a></td>
                        <td class='col-name' ><a href="{% url 'admin_app:email_detail' pk=obj.id %}">{{ obj.name }}</a></td>
                        <td class='col-email' ><a href="{% url 'admin_app:email_detail' pk=obj.id %}">{{ obj.email }}</a></td>
                        <td class="col-subject"><a href="{% url 'admin_app:email_detail' pk=obj.id %}">{{ obj.subject }}</a></td>
                        <td class='col-email-send' ><input type="checkbox" disabled {% if obj.email_send %}checked{% endif %}></td>
                        <td class='col-created-at' ><a href="{% url 'admin_app:email_detail' pk=obj.id %}">{{ obj.created_at|date:"m/d/Y" }}</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>


        <div class='paginator'>
            {% if page_obj.has_other_pages %}
                <ul>
                    {% if page_obj.has_previous %}
                    <li><a href="?page=1{% if querystring %}&{{ querystring }}{% endif %}">&lt;&lt;</a></li>
                    <li><a href="?page={{ page_obj.previous_page_number }}{% if querystring %}&{{ querystring }}{% endif %}">&lt;</a>
                    {% endif %}
    
                    <li class='active'><a class='current-page'>
                        {{ page_obj.number }}
                    </a></li>
                    
                    {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}{% if querystring %}&{{ querystring }}{% endif %}">&gt;</a></li>
                    <li><a href="?page={{ page_obj.paginator.num_pages }}{% if querystring %}&{{ querystring }}{% endif %}">&gt;&gt;</a></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>

        {# Pop-up Confirmação #}
        <div id="confirm-delete-modal" class="modal" style="display:none;">
            <div class='modal-position'>
                <div class="modal-content">
                    <p>Tem certeza que deseja deletar este registro?</p>
                    <button id="confirm-delete-yes">Sim, deletar</button>
                    <button id="confirm-delete-no">Cancelar</button>
                </div>
            </div>
        </div>
    </div>    


{% endblock content %}

admin_app/templates/admin_app/home.html
{% extends "global/base.html" %}
{% load template_filters %}
{% load static %}


{% block content %}
    {% block extra_css %}
        <link rel="stylesheet" href="{% static 'global/css/pages/admin_home.css' %}">
        <link rel="stylesheet" href="{% static 'global/css/partials/paginator.css' %}">
        <script src="{% static 'global/js/forms/pop_up_for_delete.js' %}"></script>
    {% endblock extra_css %}
    <div class='container'>
        <div class='container-title'>
            <form method='get'>
                {% if switch_state == 'projects' %}
                    <h1>{{ switch_state.title }} - Admin</h1>
                    <button type='submit' name='switch_state' value='tags'>Switch to Tags</button>
                    <a href="{% url 'admin_app:email_table' %}" class="new-register">Emails</a>
                    <a href="{% url 'admin_app:project_new' %}" class="new-register">New Project</a>
                    
                {% else %}
                    <h1>{{ switch_state.title }} - Admin</h1>
                    <button type='submit' name='switch_state' value='projects'>Switch to Projects</button>
                    <a href="{% url 'admin_app:email_table' %}" class="new-register">Emails</a>
                    <a href="{% url 'admin_app:tag_new' %}" class="new-register">New Tag</a>
                    
                {% endif %}
                    
            </form>
        </div>
        <div class='register-table-div'>
        <table class='register-table'>
            <thead>
                <tr>
                    <th class='col-id'><a href="?order_by={% if request.GET.order_by == 'id' %}-id{% else %}id{% endif %}{% if request.GET.switch_state %}&switch_state={{ request.GET.switch_state }}{% endif %}">ID</a></th>
                    <th class='col-name'><a href="?order_by={% if request.GET.order_by == 'name' %}-name{% else %}name{% endif %}{% if request.GET.switch_state %}&switch_state={{ request.GET.switch_state }}{% endif %}">NAME</a></th>
                    <th class='col-updated-at'><a href="?order_by={% if request.GET.order_by == 'updated_at' %}-updated_at{% else %}updated_at{% endif %}{% if request.GET.switch_state %}&switch_state={{ request.GET.switch_state }}{% endif %}">LAST UPDATE</a></th>
                    {% if switch_state == 'tags' %}
                    <th class='col-img-icon' >IMG</th>
                    {% else %}
                        <th class='col-visibility'><a href="?order_by={% if request.GET.order_by == 'visibility' %}-visibility{% else %}visibility{% endif %}{% if request.GET.switch_state %}&switch_state={{ request.GET.switch_state }}{% endif %}">VISIBILITY</th></a>
                        <th class='col-featured'><a href="?order_by={% if request.GET.order_by == 'featured' %}-featured{% else %}featured{% endif %}{% if request.GET.switch_state %}&switch_state={{ request.GET.switch_state }}{% endif %}">FEATURED</th></a>
                    {% endif %}
                    <th class="col-delete"></th>
                </tr>
            </thead>

            <tbody>
                {% for obj in objects %}
                    {% if switch_state == 'projects' %}
                        {% url 'admin_app:project_edit' slug=obj.slug as edit_url %}
                        {% url 'admin_app:project_delete' slug=obj.slug as delete_url %}
                    {% else %}
                        {% url 'admin_app:tag_edit' slug=obj.slug as edit_url %}
                        {% url 'admin_app:tag_delete' slug=obj.slug as delete_url %}
                    {% endif %}
                    <tr>
                        <td class='col-id' ><a href="{{ edit_url }}">{{ obj.id }}</a></td>
                        <td class='col-name' ><a href="{{ edit_url }}">{{ obj.name }}</a></td>
                        <td class='col-updated-at' ><a href="{{ edit_url }}">{{ obj.updated_at|date:"m/d/Y" }}</a></td>
                        {% if switch_state == 'tags' %}<td class='col-img-icon' ><a href="{{ edit_url }}"><img src="{{ obj.img_icon | img_or_default }}" alt="{{ obj.name }}"></a></td>{% endif %}
                        {% if switch_state == 'projects' %}
                            <td class='col-visibility' >
                                <form method="post" action="{% url 'admin_app:toggle_boolean' obj.pk 'visibility' %}">
                                    {% csrf_token %}
                                    <input type="checkbox" name="value" onchange="this.form.submit()" {% if obj.visibility %}checked{% endif %}>
                                </form>
                            </td>
                            <td class='col-featured' >
                                <form method="post" action="{% url 'admin_app:toggle_boolean' obj.pk 'featured' %}">
                                    {% csrf_token %}
                                    <input type="checkbox" name="value" onchange="this.form.submit()" {% if obj.featured %}checked{% endif %}>
                                </form>
                            </td>
                        {% endif %}
                        <td class="col-delete"><a href="#" class="btn-delete" data-url="{{ delete_url }}">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        </div>


        <div class='paginator'>
            {% if page_obj.has_other_pages %}
                <ul>
                    {% if page_obj.has_previous %}
                    <li><a href="?page=1{% if querystring %}&{{ querystring }}{% endif %}">&lt;&lt;</a></li>
                    <li><a href="?page={{ page_obj.previous_page_number }}{% if querystring %}&{{ querystring }}{% endif %}">&lt;</a>
                    {% endif %}
    
                    <li class='active'><a class='current-page'>
                        {{ page_obj.number }}
                    </a></li>
                    
                    {% if page_obj.has_next %}
                    <li><a href="?page={{ page_obj.next_page_number }}{% if querystring %}&{{ querystring }}{% endif %}">&gt;</a></li>
                    <li><a href="?page={{ page_obj.paginator.num_pages }}{% if querystring %}&{{ querystring }}{% endif %}">&gt;&gt;</a></li>
                    {% endif %}
                </ul>
            {% endif %}
        </div>

        {# Pop-up Confirmação #}
        <div id="confirm-delete-modal" class="modal" style="display:none;">
            <div class='modal-position'>
                <div class="modal-content">
                    <p>Tem certeza que deseja deletar este registro?</p>
                    <button id="confirm-delete-yes">Sim, deletar</button>
                    <button id="confirm-delete-no">Cancelar</button>
                </div>
            </div>
        </div>
    </div>    


{% endblock content %}

admin_app/templates/admin_app/project_form.html
{% extends 'global/base.html' %}
{% load template_filters %}
{% load static %}



{% block content %}
    {% block extra_css %}
        <link rel="stylesheet" href="{% static 'global/css/pages/admin_forms.css' %}">
        <script src="{% static 'global/js/forms/char_counter.js' %}"></script>
    {% endblock extra_css %}
    <div class='container-form-proj'>
        <div class="container-form">
            <h1>Project: {{ project.name }}</h1>
            <form method='post' enctype="multipart/form-data">
                {% csrf_token %}
                <div class="field">
                    <label for="{{ form.name.id_for_label }}">Project Name:</label>
                    {{ form.name }}
                </div>

                <div class="field">
                    <label for="{{ form.short_desc.id_for_label }}">Short Description:</label>
                    {{ form.short_desc }}
                    <div id="counter-short">0 / 400</div>
                </div>
                <div class="field">
                    <label for="{{ form.long_desc.id_for_label }}">Long Description:</label>
                    {{ form.long_desc }}
                    <div id="counter-long">0</div>
                </div>
                <div class="field">
                    <label class='field-label' for="{{ form.img_icon.id_for_label }}">Select icon:</label>

                    {% if form.instance.img_icon %}
                        <div class="img-field-border">
                            <div class='img-field'>
                                <span>Current file:</span>
                                <a href="{{ form.instance.img_icon.url }}">{{ form.instance.img_icon.name }}</a>
                            </div>
                            <div class='img-field'>
                                <label for="img_icon-clear_id">
                                    Remove file:
                                </label>
                                <input type="checkbox" name="img_icon-clear" id="img_icon-clear_id">
                            </div>
                            <div class='img-field'>
                                <label for="img_icon-clear_id">
                                    Modify file:
                                    <div class="img-new-field">
                                        <input type="file" name="img_icon" class="input-img" accept="image/*" id="id_img_icon">
                                        <button id="custom_file_button" type="button">Choose file:</button>
                                        <span id="file_name"></span>
                                    </div>
                                </label>
                            </div>
                        </div>
                        {% else %}
                            <div class="img-field-border">
                                <div class='img-field'>
                                    <label for="img_icon-clear_id">
                                        New file:
                                        <div class="img-new-field">
                                            <input type="file" name="img_icon" class="input-img" accept="image/*" id="id_img_icon">
                                            <button id="custom_file_button" type="button">Choose file:</button>
                                            <span id="file_name"></span>
                                        </div>
                                    </label>
                                </div>
                            </div>
                        {% endif %}
                </div>
                <div class="tags-field">
                    <label for="{{ form.tags.id_for_label }}">Select tags:</label>
                    {{ form.tags }}
                </div>

                <div class="boolean-fields">
                    <div >
                        <label for="{{ form.visibility.id_for_label }}">
                            {{ form.visibility }}
                            Is Visible?
                        </label>
                    </div>
                    <div>
                        <label for="{{ form.featured.id_for_label }}">
                            {{ form.featured }}
                            Is Featured?
                        </label>
                    </div>
                </div>
            
                <div class="button-field">
                    <button type="submit" name="action" value="save">Save</button>
                    <button type="submit" name="action" value="continue">Save and edit</button>
                </div>
            </form>
        </div>
    </div>   


{% endblock content %}